name: Keycloak 
 
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - "keycloak/**"

jobs:

  check-keycloak-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build keycloak contianer
        run: |
          cd keycloak
          docker build -t ssm-keycloak .

  publish-container-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [check-keycloak-build]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push keycloak image
        uses: docker/build-push-action@v5
        with:
          context: ./keycloak
          file: ./keycloak/Dockerfile
          push: true 
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/smart-spectral-matching/ssm-keycloak:${{ github.ref_name }}-latest
            ghcr.io/smart-spectral-matching/ssm-keycloak:${{ github.ref_name }}-${{github.sha}}
