services:
#  ssm-ui-catalog:
#    image: ssm-ui-catalog
#    restart: unless-stopped
#    environment:
#      API_URL: "http://localhost:8080/catalog/api"
#      FILE_CONVERTER_URL: "http://localhost:8080/file-converter/convert/jsonld"
#    depends_on:
#      - ssm-service-catalog
#      - ssm-service-file-converter

  ssm-ui-ml:
    image: ssm-ui-ml
    restart: unless-stopped
    network_mode: "host"  # port = 8082
    environment:
      PROFILE: "dev"

  ssm-keycloak:
    image: ssm-keycloak
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://ssm-keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      HOSTNAME: localhost 
      # HTTPS: true

  ssm-keycloak-postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres

  ssm-jupyter-ml:
    image: ssm-jupyter-ml
    restart: unless-stopped

  ssm-api-gateway:
    image: haproxytech/haproxy-alpine:2.4
    ports:
      - "8080:80"
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "./haproxy/lib/cors.lua:/etc/haproxy/cors.lua"
    depends_on:
      - ssm-ui-ml
      - ssm-service-catalog
      - ssm-service-file-converter

  ssm-service-catalog-graph-db:
    image: ghcr.io/smart-spectral-matching/ssm-service-catalog-graph-db:v0.2.0
    restart: unless-stopped
    volumes:
      - ./catalog-graph-db/databases:/opt/apache-jena-fuseki/run/databases
      - ./catalog-graph-db/backups:/opt/apache-jena-fuseki/run/backups
      - ./catalog-graph-db/configuration:/opt/apache-jena-fuseki/run/configuration
      - ./catalog-graph-db/logs:/opt/apache-jena-fuseki/run/logs
      - ./catalog-graph-db/system:/opt/apache-jena-fuseki/run/system
      - ./catalog-graph-db/system_files:/opt/apache-jena-fuseki/run/system_files
      - ./catalog-graph-db/templates:/opt/apache-jena-fuseki/run/templates

  ssm-service-catalog-document-store:
    image: mongo:4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./catalog-document-store:/data/db
  
 
  ssm-service-catalog:
    #image: ghcr.io/smart-spectral-matching/ssm-service-catalog:v0.2.0
    image: ssm-service-catalog
    restart: unless-stopped
    depends_on: 
      - ssm-service-catalog-graph-db
      - ssm-service-catalog-document-store
    command: >
      java -jar /app.jar
      -Dspring.profiles.active=localdockerfileconverter
      --app.jsonconversion=file_converter_service
      --spring.data.mongodb.host=ssm-service-catalog-document-store
      --app.fuseki.hostname=http://ssm-service-catalog-graph-db
      --app.fileconverter.uri=http://ssm-service-file-converter:8000
      --app.host=$APP_PROTOCOL://$APP_HOSTNAME:8080/catalog
      --spring.data.mongodb.username=$MONGO_USERNAME
      --spring.data.mongodb.password=$MONGO_PASSWORD
      --server.port=8080

  ssm-service-file-converter:
    #image: ghcr.io/smart-spectral-matching/ssm-service-file-converter:v0.2.3
    image: ssm-file-converter
    command: ["/usr/src/api/.venv/bin/uvicorn", "src.ssm_file_converter.app:app", "--host=0.0.0.0", "--root-path", "/file-converter"] 
 
  ssm-service-ml-database:
    image: ssm-service-ml-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
